language: ruby
rvm:
- 2.2.3
deploy:
  provider: heroku
  api_key:
    secure: E6y+1DfyMO1f9e/jDmepvhy7E9PqXgNpvJquI3xTA/tJp6I3lJb89iuAWulmj7WbbsRF1wOwTUO3K3Jhus2vhSCBwy8Drp3HZythiAbwJQhkOImuPNWTJiIT6UrS+GnvreV3LcqOmTCch4RFLy6wwA4T6TAxmGYQlhCjnOY9BQHung9YR4/yo72BNN1pAcAhKxyjLhfp3In7o3eYNHXu/sOymsh4WAH4YimEShrUeJZOlOqp8yzLfkB2nRn33OHPxR/2QADpfmwoiTmhfVMuQzx8og/6P2Cv+fvx2Is5/bx8ZJMzVqMezOna5RhHkVr7cwqN2hfr2JyQABrFsvYt80t2bmufA17L4zftFARHSYAXlu7QXjKiD/VFgFKrIS1gL+P2sHjxjCT3kC2AEtZM0z5QAnWMzO9+dTOcRMEBfIgKx9Syd7XPOvQJWxjr+VsKfLcktDSltiW0jhbHUjfFJSPVTTKZLde1PTSjI0CBi3y3oiwlJxzyVcTPoYU2DpplW/RXjYtnGRKoDzKKzE/yaTeIZFkBkGvq2GMC5qqoqY2WvcfniLacgBJ/td20gBvZtXfbUBW3J579dLd86o/gSYjrUq9ZDycfpUb+hExgC/g0Ox/W7uy1PGBX5QdjxBqoKSun8gszTivVAlhChxcHWzPqEPbp9Di2g64hXgH0+xk=
  app: matthewgyang
  on: master
